Fix: Added more tests in password.txt.
I got some failures locally, where with a non-ascii password you could
not log in, and these new tests should show the cause more clearly.

Hm, seems the failures are triggered by something else that I have
checked out.

I'll put some info here for clarity.

$ bin/test -s plone.app.users -t password.txt
...

Error in test /Users/maurits/community/plone-coredev/4.3/src/plone.app.users/plone/app/users/tests/password.txt
Traceback (most recent call last):
  File "/usr/local/pythons/parts/opt/lib/python2.6/unittest.py", line 279, in run
    testMethod()
  File "/usr/local/pythons/parts/opt/lib/python2.6/doctest.py", line 2158, in runTest
    test, out=new.write, clear_globs=False)
  File "/usr/local/pythons/parts/opt/lib/python2.6/doctest.py", line 1391, in run
    return self.__run(test, compileflags, out)
  File "/usr/local/pythons/parts/opt/lib/python2.6/doctest.py", line 1277, in __run
    got += _exception_traceback(exc_info)
  File "/usr/local/pythons/parts/opt/lib/python2.6/doctest.py", line 244, in _exception_traceback
    traceback.print_exception(exc_type, exc_val, exc_tb, file=excout)
  File "/Users/maurits/shared-eggs/zope.testrunner-4.4.4-py2.6.egg/zope/testrunner/tb_format.py", line 42, in print_exception
    file.writelines(format_exception(t, v, tb, limit))
  File "/Users/maurits/shared-eggs/zope.testrunner-4.4.4-py2.6.egg/zope/testrunner/tb_format.py", line 31, in format_exception
    return fmt.formatException(t, v, tb)
(Recursive formatException() stopped, trying traceback.format_tb)
  File "/Users/maurits/shared-eggs/zope.exceptions-3.6.2-py2.6.egg/zope/exceptions/exceptionformatter.py", line 177, in formatException
    line = self.formatLine(tb)
  File "/Users/maurits/shared-eggs/zope.exceptions-3.6.2-py2.6.egg/zope/exceptions/exceptionformatter.py", line 122, in formatLine
    line = linecache.getline(filename, lineno)
  File "/Users/maurits/pythons/2.6/lib/python2.6/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/local/pythons/parts/opt/lib/python2.6/doctest.py", line 1336, in __patched_linecache_getlines
    source = example.source.encode('ascii', 'backslashreplace')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 70: ordinal not in range(128)

Totally not helpful.
Showing only the first error works better:

$ bin/test -s plone.app.users -t password.txt -1
...
File "/Users/maurits/community/plone-coredev/4.3/src/plone.app.users/plone/app/users/tests/password.txt", line 61, in password.txt
Failed example:
    'Login failed' in self.browser.contents
    Expected:
        False
    Got:
        True